
services:

  postgres:
    image: postgres
    ports:
     - 5432:5432
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile 
      network: host
    ports:
      - 5173:5173
    depends_on:
      - backend

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile 
      network: host
    ports:
      - 3000:3000
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - postgres